; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = main
default_envs = lolin32_lite

[env:dfrobot_beetle_esp32c3]
platform = espressif32
board = dfrobot_beetle_esp32c3
framework = espidf

build_unflags =
    -std=gnu++11
    -std=gnu++17

; enable C++ 23
build_flags =
    -std=gnu++23
;    -DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG

; build_type = debug

board_build.partitions = partitions.csv
board_build.embed_txtfiles = components/web_server/web_ui/index.html


[env:lolin32_lite]
platform = espressif32
board = lolin32
framework = espidf
monitor_speed = 115200

build_unflags =
    -std=gnu++11
    -std=gnu++17

build_flags =
    -std=gnu++23

board_build.partitions = partitions.csv
board_build.embed_txtfiles = components/web_server/web_ui/index.html

# Target the specific local agent name you initialized in Step 1
remote_agent = local_desk

# Optional: Specify the local USB port if auto-detection fails
# upload_port = COM10